name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.9.0'  # Specify the Node.js version you want to use

      - name: Clean npm cache 
        run: | 
          cd frontend
          npm cache clean --force

      - name: Install dependencies
        run: | 
          cd frontend
          npm install

      - name: Install Angular CLI
        run: |
          cd frontend
          npm install -g @angular/cli@17.3.6
          npm install --save-dev @angular-devkit/build-angular:application

      - name: Print environment variables 
        run: env

      - name: Build the application
        run: |
          cd frontend
          ng build -- --configuration production --base-href "https://aneevel.github.io/SoftwarePlanner"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/src/browser/
