name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.9'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build -- --configuration production --base-href "https://aneevel.github.io/SoftwarePlanner"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../../frontend/dist/src/browser/
